### ISSUE TITLE
Cannot create concepts in huggingface space

### ISSUE THREAD

**Issue by ajms** [lilacai/lilac#1027]
Hi,

I have tried to create huggingface spaces for lilac (0.2.0)  by using option 2 and 3 in [docs](https://docs.lilacml.com/deployment/huggingface_spaces.html).

When I create a concept locally and use option 2, the concept is not available in the huggingface space. 
Generally, the option to create a new concept is greyed out. 
When I create a new concept through the search bar, I get 
```
details
    lilac.auth.ConceptAuthorizationException: Concept namespace "local" does not exist or user does not have access.
url
    POST /api/v1/concepts/create
status
    500
path
    undefined
body
    {
      "namespace": "local",
      "name": "test",
      "type": "text",
      "metadata": {
        "description": "test"
      }
    }
```
Are concepts only available locally at this point?

**Comment by nsthorat** [comment]
Hi @ajms, is this in your own space, not in our space?

Can you try removing authentication in your settings? Just remove the "LILAC_AUTH_ENABLED" bit.

**Comment by ajms** [comment]
Hi @nsthorat, 
Thank you, removing lilac_auth_enabled did the trick.
