### ISSUE TITLE
can we add this open source multilingual embedding model?

### ISSUE THREAD

**Issue by kostum123** [lilacai/lilac#1148]
It would be nice if we add this model as a multilingual embedding model.

https://huggingface.co/BAAI/bge-m3

**Comment by kostum123** [comment]
> Happy to do this -- is there a particular size you care most about?

There is currently only one version for the multilingual version, it has 568M parameters.  It has 3 modes in 1 model: dense retrieval, multi-vector(colbert like) retrieval, and sparse retrieval.  It seems to be the best among open source multilingual models.  It can produce embedding with a combination of 3 modes and has a context length of 8k.  I think Lilac's addition of such a model would be an alternative for users who want to use it in multilingual datasets.

![imgs_miracl](https://github.com/lilacai/lilac/assets/34637927/968dbdaf-b465-41f9-a60b-d9f5363c73f7)
![imgs_mkqa](https://github.com/lilacai/lilac/assets/34637927/91b0b38e-8ae0-4f16-82ac-baa23d6b8f45)

**Comment by nsthorat** [comment]
bge-m3 is supported in https://github.com/lilacai/lilac/releases/tag/v0.3.5
