### ISSUE TITLE
Histograms are not visually correct.

### ISSUE THREAD

**Issue by nsthorat** [lilacai/lilac#1161]
<img width="718" alt="image" src="https://github.com/lilacai/lilac/assets/1100749/39e75098-bece-4c81-a2e3-98efdc2e8e40">

The 1 and the 155 are the same length.

**Comment by dsmilkov** [comment]
It's visually correct for a linear scale. We can add a little toggle between linear and log scale to resolve this.

**Comment by dsmilkov** [comment]
Alternatively, what @brilee suggested, which is to ignore the min/max when determining buckets, and use 10/90%-tiles for the first and last bucket
