### ISSUE TITLE
There is no place in UI to select input field for clustering 

### ISSUE THREAD

**Issue by sworddish** [lilacai/lilac#1187]
I tried to upload a simple jsonl to do the clustering, the data format is pure jsonl with my self-defined field. 

I have to manually set the options.input before running run_server_prod.sh, otherwise I will got the error as followings

File "/lilac/lilac/router_dataset_signals.py", line 129, in cluster
    raise ValueError('Dataset format is not defined.')

**Comment by mrorii** [comment]
I started seeing the same error recently. Based on the fact that I see such an error on https://github.com/lilacai/lilac/commit/8e7418d533e6fba64ef1854e4112e66c035321bf but not on https://github.com/lilacai/lilac/commit/78f0c551be54eb3d49f981d5b16fd607bc79bf58, my guess is that a bug may have been introduced in https://github.com/lilacai/lilac/pull/1185?

**Comment by nsthorat** [comment]
Sorry about that, you are right. Will fix it today.

**Comment by nsthorat** [comment]
Should be fixed in 0.3.6
