### ISSUE TITLE
Python duckdb error when filtering to no results and sorting by a concept score.

### ISSUE THREAD

**Issue by nsthorat** [lilacai/lilac#316]
<img width="1478" alt="image" src="https://github.com/lilacai/lilac/assets/1100749/4e1efc68-4b8e-4d50-bf9f-aa1f8620e4fb">

This is coming from no results being passed to the concept for scoring (this is now testable via a search query that has no results).

**Comment by brilee** [comment]
not sure if this is still a bug

**Comment by nsthorat** [comment]
Looks fixed.
