### ISSUE TITLE
Show explicit NaNs in group by.

### ISSUE THREAD

**Issue by nsthorat** [lilacai/lilac#415]
Currently we ignore NaN for all histograms. Let's add a way to explicitly have NaNs shown.

**Comment by brilee** [comment]
<img width="396" alt="Screenshot 2024-02-06 at 11 19 48 AM" src="https://github.com/lilacai/lilac/assets/1320214/f6b1425d-7bed-4879-bfbf-d54b19e0440d">
fixed to look more like this, btw...
