### ISSUE TITLE
Use opensource models for curation

### ISSUE THREAD

**Issue by fire** [lilacai/lilac#599]
As part of https://llm-efficiency-challenge.github.io/

I want to propose a workflow that uses lilac and a less capable but opensource model.

Rules relevant:

    Submissions must be reproducible from initial model through fine tuning and inference. Winning models, along with all associated code and data, must be open-sourced and made public after the competition.

    Submissions must NOT use any copyrighted or proprietary data, code, or closed-source content. The use of data or content that breaks service contracts or trade secrets of any entity is not allowed.

https://llm-efficiency-challenge.github.io/rules

**Comment by msaroufim** [comment]
Hi @nsthorat! I'm one of the competition organizers, one of the most active discussions in our discord chat has been on which datasets are allowed for the competition here https://discord.com/channels/1124130156336922665/1137300391038570518

Specifically the competition limits the base model but does not limit the dataset, we cannot however accept datasets that are derived from places where the license does not permit it example ChatGPT or LLAMA 70B. There are obviously some popular datasets already people can use which we highlight here https://llm-efficiency-challenge.github.io/challenge but I'm optimistic that one of the top entries will do something clever with the way they create or curate data

Some ideas for us to collaborate more concretely might be an example of how to do data curation here https://github.com/llm-efficiency-challenge/neurips_llm_efficiency_challenge, you can come in and give a talk on our Discord channel and if there's anything else you think would be helpful for competitors please let me know!

**Comment by nsthorat** [comment]
Thanks for sharing! Happy to come and join the discord to discuss how we can be helpful. Is there a public invite link somewhere (the link above says no text channels)?
