### ISSUE TITLE
ERROR: Failed building wheel for pyarrow

### ISSUE THREAD

**Issue by dzhulianaN** [lilacai/lilac#604]
Building wheels for collected packages: pyarrow
  Building wheel for pyarrow (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pyarrow (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [215 lines of output]

 note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyarrow
Failed to build pyarrow
ERROR: Could not build wheels for pyarrow, which is required to install pyproject.toml-based projects

**Comment by zach-brockway** [comment]
I hit this on my M1 laptop as well, and after spending a little time on it, cannot recommend trying to go the build from source route. Much easier to `conda install -c conda-forge pyarrow==9.0`. No other requirements gave me trouble via pip.

**Comment by dsmilkov** [comment]
hi all, if you can share your OS, python version, and arch (arm vs x86) that would be great. We are about to update pyarrow to latest (13.x) which might help.

**Comment by nsthorat** [comment]
I was able to repro this on my older M1. We just upgraded pyarrow to 13.x which resolved this.

Feel free to reopen if you still see the issue after the upgrade!
