### ISSUE TITLE
Opening lilac on local network

### ISSUE THREAD

**Issue by Orsucciu** [lilacai/lilac#607]
Hello,

I am trying to use lilac on my remote server.

I tried starting it from cli (lilac start) and then joining it through its ip adress, as well as using the python console to run lilac.server_start with options set to 0.0.0.0 as well as the ip of the server. Neither solutions give me errors in the console, but the server is unreachable.

I am using debian, with python 3.11 if that's relevant.

Thanks

**Comment by nsthorat** [comment]
Hi @Orsucciu, can you try explicitly passing `--host 0.0.0.0 --port 3000` (or whatever port you want)?

**Comment by dsmilkov** [comment]
The default Lilac port is `5432` so I just want to double check that you tried `remote_ip:5432`?

**Comment by Alx-AI** [comment]
If you're using default settings, while it may say ``` Uvicorn running on http://0.0.0.0:5432``` navigating to http://localhost:5432/ instead might solve your issue

**Comment by Orsucciu** [comment]
Hi, i just ran `lilac start --host 0.0.0.0 --port 4321` but when i get the ip directly (http://ip:port), i still get no answer (maybe this is a config problem, and not a lilac one tho!). The console doesn't send any errors either, my last lilac messages are 
`INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:4321 (Press CTRL+C to quit)`

**Comment by nsthorat** [comment]
This should now be fixed at https://github.com/lilacai/lilac/releases/tag/v0.0.15, we now default to 127.0.0.1 so it should open to local 127.0.0.1 without the 0.0.0.0 interface.

Let me know if you have issues after upgrading
