### ISSUE TITLE
Lilac projects: lilac.yml, lilac init, loading upon boot.

### ISSUE THREAD

**Issue by nsthorat** [lilacai/lilac#619]
The proposal:

```
lilac start ~/my_project
```

This will initialize a lilac project inside `~/my_project` if it doesn't and start the webserver.

Users can add a `~/my_project/lilac.yml` file which will be loaded the next time the server starts (or via a call to `lilac load`).

When users interact with the UI, `lilac.yml` will *not* automatically be updated, unless there is an explicit call to an API or via the UI to update it (or if we have an explicit share). Each dataset will contain a private `config.yml` file which reflects any calls to API from python or the UI, allowing us to diff the `lilac.yml` with changes from each dataset.

On HuggingFace, we'll make a `demo` folder, and point the call to `lilac start` to that folder.

**Comment by brilee** [comment]
I think this is fixed? @nsthorat can you confirm

**Comment by nsthorat** [comment]
Yes, fixed.
