### ISSUE TITLE
Search box should enable search by signals even when embeddings are not computed.

### ISSUE THREAD

**Issue by nsthorat** [lilacai/lilac#623]
Currently we don't let you search by anything over a media field unless you compute an embedding.

**Comment by dsmilkov** [comment]
I can't repro this at HEAD. E.g. the screenshot below shows `premise` has no embeddings, but has pre-computed PII, and we can search by PII.

<img width="1032" alt="image" src="https://github.com/lilacai/lilac/assets/2294279/f7452bb7-80ab-46e2-95f0-73319c746ae9">

**Comment by dsmilkov** [comment]
Or is the proposal to show "Compute PII" as an option?

**Comment by nsthorat** [comment]
Oh you're right! However, we dropped keyword search -- which is why I thought this was broken

**Comment by dsmilkov** [comment]
Yeah, keyword search only shows up when you have non-empty input
