### ISSUE TITLE
"ValueError: Cannot merge source  ... into destination ..." when computing signal 

### ISSUE THREAD

**Issue by chilang** [lilacai/lilac#646]
Hi,
I'm hitting this issue when trying to compute a signal for a text field 
<img width="1102" alt="Screenshot 2023-09-05 at 15 33 51" src="https://github.com/lilacai/lilac/assets/7852/cf60395e-aeed-457d-94e9-97f1fe93d9ba">
I'm running a local instance of lilac 0.0.17 `pip install lilac`.
This seems to happen to multiple instances of data (UI shows multiple ApiError popups)

**Comment by nsthorat** [comment]
Thanks for filing this -- on it. What type of machine are you using (win/mac/linux)?

**Comment by chilang** [comment]
Linux Ubuntu 22.04.2

**Comment by nsthorat** [comment]
The fix is out in https://github.com/lilacai/lilac/releases/tag/v0.0.18

**Comment by chilang** [comment]
Upgraded to 0.0.18 and I'm getting this when previewing signal
<img width="916" alt="Screenshot 2023-09-06 at 21 20 45" src="https://github.com/lilacai/lilac/assets/7852/5477ee98-66b0-43a4-b94b-e8d526acf8fc">
Is 0.0.18 backward compatible? In case it's spacy version related, here is my 
```
pip freeze | grep spacy
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.6.0/en_core_web_sm-3.6.0-py3-none-any.whl#sha256=83276fc78a70045627144786b52e1f2728ad5e29e5e43916ec37ea9c26a11212
spacy==3.5.4
spacy-legacy==3.0.12
spacy-loggers==1.0.4
```

**Comment by dsmilkov** [comment]
Interesting... Looking at the stack trace in the screenshot, it looks like the error happens in the `confection` library (a dependency of `spacy`) when trying to load a cached spacy model from disk. I wonder if the spacy version had changed in a way that causes loading of an older cached language model to fail.

**Comment by nsthorat** [comment]
@chilang to test that theory, can you try `pip uninstall en-core-web-sm`

When you run anything that uses spacy again it will redownload the latest version.

**Comment by chilang** [comment]
That did the trick! Thanks @nsthorat @dsmilkov
