### ISSUE TITLE
"AttributeError: 'LogisticRegression' object has no attribute 'coef_'" when selecting pre-computed concept

### ISSUE THREAD

**Issue by chilang** [lilacai/lilac#648]
Hi,
I'm getting this error when selecting a pre-computed concept `lilac/negative-sentiment` on a local lilac install (version 0.0.17, venv+Python 3.10)
<img width="1135" alt="Screenshot 2023-09-05 at 15 50 23" src="https://github.com/lilacai/lilac/assets/7852/d8618e02-4eb9-4620-b29b-4549feee3031">
This seems to be happening with only some concepts, `negative-sentiment`, `legal-termination` while others are fine, eg. positive-sentiment, toxicity etc.

Attached is my pip freeze in case it helps in reproducing
[requirements.txt](https://github.com/lilacai/lilac/files/12525087/requirements.txt)

**Comment by nsthorat** [comment]
The fix is out in https://github.com/lilacai/lilac/releases/tag/v0.0.18
