### ISSUE TITLE
Option to remove or restirct label all

### ISSUE THREAD

**Issue by conceptofmind** [lilacai/lilac#730]
Hello,

Is there an available option to remove the label all button?

If a server is shared with numerous individuals in would help to restrict certain features.

Thank you,

Enrico

**Comment by nsthorat** [comment]
Hi Enrico,

You can set the "LILAC_AUTH_ENABLED" environment flag to true which will disable editing any dataset (labels, computing signals, deleting signals, deleting the dataset, changing settings).

Let me know if you need more fine grained control, or if this flag doesn't quite do what you want!

**Comment by conceptofmind** [comment]
> Hi Enrico,
> 
> You can set the "LILAC_AUTH_ENABLED" environment flag to true which will disable editing any dataset (labels, computing signals, deleting signals, deleting the dataset, changing settings).
> 
> Let me know if you need more fine grained control, or if this flag doesn't quite do what you want!

Hi,

Thank you for the response.

I would not want to disable all functionality. If I have one server with 3 collaborators. I would still want them to be able to utilize the functions. I would want finer grain control for disabling things such as the `download` button or the `label all` button except for administrators. 

I think that the `label all` button can be a point of failure during collaboration if one authorized member accidentally or purposefully chooses to overwrite all the labels others have done with one click. 

Lilac is a phenomenal project and I am very excited to see it continue to grow.

Thank you,

Enrico

**Comment by nsthorat** [comment]
Got it -- I can work on that this week!

For "admin" vs "non-admin" -- is authentication via Google login okay? You could configure an admin to be a set of emails / google IDs, and we'd use oauth to authenticate users (like we do on the HuggingFace space).

Nothing is stored on disk about login information (it's all in-memory in the webserver), except for when a user creates a concept after being logged in -- the namespace corresponds to their unique Google OAuth ID.

**Comment by conceptofmind** [comment]
> Got it -- I can work on that this week!
> 
> For "admin" vs "non-admin" -- is authentication via Google login okay? You could configure an admin to be a set of emails / google IDs, and we'd use oauth to authenticate users (like we do on the HuggingFace space).
> 
> Nothing is stored on disk about login information (it's all in-memory in the webserver), except for when a user creates a concept after being logged in -- the namespace corresponds to their unique Google OAuth ID.

Hi,

I believe Google login should be okay. Some of the collaborators are Japanese and Korean natives but I do not think that should be an issue for accessing Google login.

If collaborators are still able to use predefined labels set by the administrator in the UI but have restricted access to everything else (concepts, download, label all, adding new labels, etc.) that would be very useful. Then an administrator could define additional access to certain parts of the application depending on the user and permissions that are set for them. 

Thank you again for all of your great work!

Enrico

**Comment by nsthorat** [comment]
Working on this now -- is there anything in particular you would want non-admin users to be able to *edit*?

**Comment by conceptofmind** [comment]
> Working on this now -- is there anything in particular you would want non-admin users to be able to _edit_?

I would want non-admin users to be able to select from a pre-defined set of labels, such as 0 or 1.

An example workflow:

1. A collaborator accesses the provided URL to the user interface.
2. They log in using Google authorization.
3. They can see the available dataset provided by the administrator.
4. They are able to select from a set of predefined labels, in this case 0 or 1.
5. They can apply that 0 or 1 label to a singular example from the dataset at a time.
6. They do not have any other access to edit unless it is specifically granted to that user.

I think being able to enforce a rigid structure such as the above will help to limit a lot potential failures during collaboration.

**Comment by nsthorat** [comment]
Pending PR which adds a new flag `LILAC_AUTH_USER_EDIT_LABELS` allowing only admins to create label types, and users can only add labels https://github.com/lilacai/lilac/pull/734

In your case, the admin will create two labels "0" and "1" (currently we only have "tagging" in the UI, not an enum value).

Let me know if this works.

BTW -- for the one bit about downloading, do you need to restrict that? In theory users could actually download the whole dataset because that's how the UI is powered (hitting the REST endpoint).

**Comment by conceptofmind** [comment]
> Pending PR which adds a new flag `LILAC_AUTH_USER_EDIT_LABELS` allowing only admins to create label types, and users can only add labels #734
> 
> In your case, the admin will create two labels "0" and "1" (currently we only have "tagging" in the UI, not an enum value).
> 
> Let me know if this works.
> 
> BTW -- for the one bit about downloading, do you need to restrict that? In theory users could actually download the whole dataset because that's how the UI is powered (hitting the REST endpoint).

Hi,

The tagging works great. It does not need to be an enum value.

As long as the collaborators can not use the `label all` button but can still add pre-defined labels to samples in UI then it would be perfect.

I think it would be useful to restrict the download button but it is not something that is a necessary feature at this point. Thank you for the information about hitting the REST endpoint.

**Comment by nsthorat** [comment]
I see, so you also want the label all button to be **disabled**, but the individual row labeling to be **enabled**?

Happy to do that, just curious the motivation! Maybe it's that we should actually just disabled "Label All" when there are no filters, since this is useful for multi-labeling a slice (e.g. readability > 200)

**Comment by conceptofmind** [comment]
> I see, so you also want the label all button to be **disabled**, but the individual row labeling to be **enabled**?
> 
> Happy to do that, just curious the motivation! Maybe it's that we should actually just disabled "Label All" when there are no filters, since this is useful for multi-labeling a slice (e.g. readability > 200)

Yes exactly! Disable the label all button while still allowing for logged-in individuals to label specific rows.

The biggest issue is that an individual could get access to a link and then overwrite all the labels other collaborators have worked on from my understanding.

Say you have 3 collaborators who have been working on labeling individual rows of a dataset with binary annotations. Collaborators 1 and 2 continue to label the rows without any issues. Collaborator 3 accidentally or purposefully decides to label all the rows ruining the work that others have done. Or one of the collaborators shares the URL with someone outside the project who maliciously decides to label all annotations incorrectly.

These are just some things I have been thinking about when working with groups of annotators.

**Comment by nsthorat** [comment]
Makes sense! I will do that. Everything else but that is done now (not yet released).

Ideally the solution is to tie a label to a user, but that requires a little more thought (since user data is purely an in-memory server thing right now).

**Comment by nsthorat** [comment]
Alright, 3 PRs landed for this and released in 0.1.15:

https://github.com/lilacai/lilac/releases/tag/v0.1.15

New environment flags:
- `LILAC_AUTH_ADMIN_EMAILS`: a comma-separated list of google oauth emails
- `LILAC_AUTH_USER_EDIT_LABELS`: Allow non-admins to add/remove labels. This should be 'True' for you.
- `LILAC_AUTH_USER_DISABLE_LABEL_ALL`: Disable label-all functionality. This should be 'True' for you.

Unit test here: https://github.com/lilacai/lilac/blob/v0.1.15/lilac/server_test.py#L115

**Comment by conceptofmind** [comment]
Ok. Awesome. I will pull the latest and test it out.

Thank you!
