### ISSUE TITLE
Simple docker command in readme / getting started

### ISSUE THREAD

**Issue by josephrocca** [lilacai/lilac#737]
This project is really neat! I'm using it to help build a toxicity classifier for a comments moderation system.

Question: Can you add a simple docker command to the readme or quickstart/installation guide? If I click the three vertical dots on the Hugging Face space and click "Run with Docker" (in the same menu as the "Duplicate this Space" button) then it gives me this command:
```
docker run -it -p 7860:7860 --platform=linux/amd64 \
	-e HF_ACCESS_TOKEN="YOUR_VALUE_HERE" \
	-e GOOGLE_CLIENT_SECRET="YOUR_VALUE_HERE" \
	-e LILAC_OAUTH_SECRET_KEY="YOUR_VALUE_HERE" \
	-e DUCKDB_USE_VIEWS="1" \
	-e HF_HOME="/data/.huggingface" \
	-e _SEE_LILAC_DOCS_="https://lilacml.com/huggingface/huggingface_spaces.html" \
	-e LILAC_PROJECT_DIR="/data" \
	-e TRANSFORMERS_CACHE="/data/.cache" \
	-e XDG_CACHE_HOME="/data/.cache" \
	-e GOOGLE_ANALYTICS_ENABLED="true" \
	-e LILAC_AUTH_ENABLED="true" \
	-e GOOGLE_CLIENT_ID="279475920249-i8llm8vbos1vj5m1qocir8narb3r0enu.apps.googleusercontent.com" \
	registry.hf.space/lilacai-lilac:latest
```
Which I trimmed down to this since I don't need any auth/access-token stuff:
```
docker run -it -p 7860:7860 --platform=linux/amd64 \
	-e DUCKDB_USE_VIEWS="1" \
	-e HF_HOME="/data/.huggingface" \
	-e _SEE_LILAC_DOCS_="https://lilacml.com/huggingface/huggingface_spaces.html" \
	-e LILAC_PROJECT_DIR="/data" \
	-e TRANSFORMERS_CACHE="/data/.cache" \
	-e XDG_CACHE_HOME="/data/.cache" \
	-e LILAC_AUTH_ENABLED="false" \
	registry.hf.space/lilacai-lilac:latest
```
But for some reason the port was wrong - I had to switch it to `5432`. And I also had to add a `--volume` mount.

So it wasn't too hard to get working, but it would be great it the readme could have a simple, trimmed-down docker command to make it easier for people like me to quickly try out Lilac. Thanks!

**Comment by josephrocca** [comment]
Oh, but that doesn't use GPU - need to add `--gpus all`. So the final command I'm using is:

```
docker run -it --gpus all --volume /home/joe/Downloads/lilac-data:/data -p 5432:5432 --platform=linux/amd64 \
        -e DUCKDB_USE_VIEWS="1" \
        -e HF_HOME="/data/.huggingface" \
        -e _SEE_LILAC_DOCS_="https://lilacml.com/huggingface/huggingface_spaces.html" \
        -e LILAC_PROJECT_DIR="/data" \
        -e TRANSFORMERS_CACHE="/data/.cache" \
        -e XDG_CACHE_HOME="/data/.cache" \
        -e LILAC_AUTH_ENABLED="false" \
        registry.hf.space/lilacai-lilac:latest
```

**Comment by josephrocca** [comment]
@dsmilkov Could a pre-built image be added so that it's just a one-liner for people to try it out?

**Comment by dsmilkov** [comment]
Closing since we did this in https://github.com/lilacai/lilac/pull/753 and docker images are here https://hub.docker.com/r/lilacai/lilac/tags

(soon: we will probably get rid of pytorch as dependency and go with converted onnx models to reduce binary size and make it work more easily on several platforms)
