### ISSUE TITLE
Crashed after embedding ~32k docs and progress lost - "Worker with pid 120 was terminated due to signal 4"

### ISSUE THREAD

**Issue by josephrocca** [lilacai/lilac#738]
I loaded a CSV and then started embedding - after 8 mins it crashed. Here are the logs:
```
MPS not available because the current PyTorch install was not built with MPS enabled.
Downloading (…)2e6d8/.gitattributes: 100%|█████████████████████████████████████████████████████| 1.52k/1.52k [00:00<00:00, 313kB/s]
Downloading (…)_Pooling/config.json: 100%|████████████████████████████████████████████████████████| 190/190 [00:00<00:00, 89.0kB/s]
Downloading (…)9e0ce2e6d8/README.md: 100%|████████████████████████████████████████████████████| 68.1k/68.1k [00:00<00:00, 17.5MB/s]
Downloading (…)0ce2e6d8/config.json: 100%|█████████████████████████████████████████████████████████| 583/583 [00:00<00:00, 271kB/s]
Downloading pytorch_model.bin: 100%|███████████████████████████████████████████████████████████| 66.8M/66.8M [00:00<00:00, 111MB/s]
Downloading (…)nce_bert_config.json: 100%|██████████████████████████████████████████████████████| 57.0/57.0 [00:00<00:00, 28.7kB/s]
Downloading (…)cial_tokens_map.json: 100%|████████████████████████████████████████████████████████| 125/125 [00:00<00:00, 61.9kB/s]
Downloading (…)2e6d8/tokenizer.json: 100%|██████████████████████████████████████████████████████| 712k/712k [00:00<00:00, 2.86MB/s]
Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████████████████████| 394/394 [00:00<00:00, 189kB/s]
Downloading (…)9e0ce2e6d8/vocab.txt: 100%|██████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 45.6MB/s]
Downloading (…)ce2e6d8/modules.json: 100%|█████████████████████████████████████████████████████████| 385/385 [00:00<00:00, 191kB/s]
[local/comments-plugin-messages] Compute signal "gte-small" on "message":   1%|         | 32740/5864767 [08:15<22:36:09, 71.67it/s][2023-10-04 07:33:03 +0000] [64] [WARNING] Worker with pid 120 was terminated due to signal 4
[2023-10-04 07:33:03 +0000] [303] [INFO] Booting worker with pid: 303
[2023-10-04 07:33:03 +0000] [303] [INFO] Started server process [303]
[2023-10-04 07:33:03 +0000] [303] [INFO] Waiting for application startup.
[2023-10-04 07:33:03 +0000] [303] [INFO] Application startup complete.
```

And it doesn't seem to keep progress? I had to start over when it rebooted - guessing it's going to crash again. Work should ideally resume after crashes - since embedding these 5 million messages would be a 24 hour job, and it's possible that the machine crashes for some other reason, in which case I'd have to start over, regardless of whether this particular "signal 4" bug is fixed.

**Comment by josephrocca** [comment]
Just tried again and it crashed at exactly 32740 once again. Any idea what might cause that? Maybe it's hitting a row of the CSV that has bad data (e.g. malformed unicode, or something)? Not sure how to inspect that 32,740th document.

**Comment by dsmilkov** [comment]
Thanks for filing! Signal 4 means illegal instruction, which means it's probably in compiled / binary code, which comes either from our `DuckDB`, `HNSW` or `Torch` dependencies. Do you mind sharing the 32,740th +/- 2 rows from that csv so we can reproduce on our side?

You can do something like:
```
head -n 32742 csv.txt | tail -n +32738 > new_csv.txt
```

**Comment by nsthorat** [comment]
32740 is exactly how much we chunk embeddings before writing to a vector store, so my suspicion is actually in hnsw, not in duckdb/torch, and not on your 32740th row.

What kind of machine are you on?

**Comment by josephrocca** [comment]
Anything I can do to help solve this? I just reproduced this with [this dummy data](https://gist.githubusercontent.com/josephrocca/539329c895821bb020b7cdde4e37c8e1/raw/2c84a785bb77db7941a61e65d8594d138892bed6/dummy.csv), on Ubuntu 22.04 and using this exact Docker command:
```
docker run -it --volume /home/joe/Downloads/lilac-data:/data -p 5432:5432 --platform=linux/amd64 \
        -e DUCKDB_USE_VIEWS="1" \
        -e HF_HOME="/data/.huggingface" \
        -e _SEE_LILAC_DOCS_="https://lilacml.com/huggingface/huggingface_spaces.html" \
        -e LILAC_PROJECT_DIR="/data" \
        -e TRANSFORMERS_CACHE="/data/.cache" \
        -e XDG_CACHE_HOME="/data/.cache" \
        -e LILAC_AUTH_ENABLED="false" \
        registry.hf.space/lilacai-lilac:latest
```
I put `dummy.csv` in that `/home/joe/Downloads/lilac-data` folder, then loaded the CSV, then clicked in the search bar and clicked "compute embeddings".

After a couple of minutes I got this:
```
[local/dummy] Compute signal "gte-small" on "message":  33%|█▎  | 32704/100000 [02:41<05:35, 200.78it/s][2023-10-06 01:08:52 +0000] [64] [WARNING] Worker with pid 120 was terminated due to signal 4
```
So, `32704` this time - guessing it's the exact same issue though.

**Comment by josephrocca** [comment]
Oh and I just realised it wasn't using my GPU so I added `--gpus all` to the command in case that was the problem, but the same error occurred (but 10x faster :sunglasses:).

**Comment by dsmilkov** [comment]
Thanks for testing this! What happens if you remove the `--platform=xxx` flag? When I removed it on my MacBook M1 machine I got:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected
host platform (linux/arm64/v8) and no specific platform was requested
```

This means that HuggingFace pre-built the image on Linux and it will likely crash on ARM since QEMU emulation is very buggy. I'll now try to build my own docker on my platform. Once I do that I will document it in https://github.com/lilacai/lilac/issues/737

**Comment by josephrocca** [comment]
I'm running on linus/amd64 so I didn't get that error. I tried removing it anyway, but this time it hangs while loading the dataset:

![image](https://github.com/lilacai/lilac/assets/1167575/3645390c-4642-4a9d-a041-5d3b295f54d8)

But I'm guessing this is due to a separate bug in the latest release or something?

**Comment by josephrocca** [comment]
I also just tried the readme docker instructions and got the same problem - hangs indefinitely on "100,000/100,000".

**Comment by josephrocca** [comment]
Seems to have fixed it! Works fine with CPU now using a fresh `git clone` of this repository and using the readme docker command. But when I add `--gpus all` I get this message at startup:

```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.
ERRO[0000] error waiting for container:
```
Whereas previously `--gpus all` was working fine (and inference was 10x faster so it was actually utilising the GPUs).

**Comment by josephrocca** [comment]
Oh, wait scratch that! `--gpus all` work fine. But for some reason I have to make sure Docker Desktop is not running (I haven't looked into it but I'm pretty sure it's related to [this post](https://forums.docker.com/t/nvidia-cuda-doesnt-work-on-docker-desktop-but-works-on-docker-engine/130668)), otherwise I get that error in my previous comment. That error is not specific to the Lilac docker image, since it occurs with a basic Ubuntu 20.04 CUDA image that I just tried too. 

So this all seems to be working properly now - thank you! Excited to try this out :partying_face:
