### ISSUE TITLE
Button and text area styling is kinda strange / counterintuitive

### ISSUE THREAD

**Issue by josephrocca** [lilacai/lilac#756]
This was bit confusing for me. I don't think it's worth trying to innovate too much on the styling/layout of basic elements like buttons and text inputs here:

![image](https://github.com/lilacai/lilac/assets/1167575/52259ec3-aa1f-4eb9-8ddd-0a942f8b906b)

The default way that the browser displays buttons and inputs is better than this, I think - at the very least, the text inputs should have outlines around them so it's clear that they exist.

**Comment by dsmilkov** [comment]
I agree! Thanks for filing. Improved in https://github.com/lilacai/lilac/pull/763
