### ISSUE TITLE
Can't... do anything

### ISSUE THREAD

**Issue by enn-nafnlaus** [lilacai/lilac#761]
Just thought I'd give lilac a try for cleaning my datasets.  Unfortunately I hit a stumbling block right off the bat:

![image](https://github.com/lilacai/lilac/assets/116288799/f79d2899-c3cd-4643-96ea-5e3e885ee5af)

First I couldn't search by output, but I found how to enable that in "administration"You'll note that my dataset has "instruction" and "output". But when I find something I'm not happy with... there's nothing I can do with I can't edit it.  I can't delete it.  It's just... there, in the search results.  The only thing I seem to have an option to do is "Label all", but that fails

![image](https://github.com/lilacai/lilac/assets/116288799/3757f4de-1c9f-4c13-8948-9b81e6fb9b4f)

Lilac is running as the same user that created and owns the json files, there's no issues with them not being accessible.

ED: Looks like I can create individual labels, just not label all.  But what good is that?  If there's bad data, I need to edit or delete it.

**Comment by nsthorat** [comment]
@enn-nafnlaus so sorry that this is happening.

Is this from a fork of the HuggingFace space, or are you running it locally?

Can you remove the LILAC_AUTH_ENABLED environment variable which is disabling all of these features (either locally or on HF)?

**Comment by enn-nafnlaus** [comment]
Running locally.
LILAC_AUTH_ENABLED is not set in my environment

I restarted and was able to do label_all, but labeling is still the only feature I'm able to do. Which just created a new problem, as in my test I did label_all "Test", and all 40k rows got labeled "Test", but now I can't remove the labels except one at a time.

**Comment by nsthorat** [comment]
Thanks for the feedback -- we'll add a batch delete and improve onboarding with media / metadata fields.

For now, you can delete all of those labels if into the project directory you can delete the labels sqlite file (e.g. my_label.labels.sqlite under project_dir/datasets/local/summarize) and refresh (label all is going to label the entire slice that's currently selected, with no filters it's the entire dataset).

You can also remove a subset of them from python with: [`dataset.remove_labels`](https://lilacml.com/api_reference/data.html#lilac.data.Dataset.remove_labels)

**Comment by enn-nafnlaus** [comment]
Thanks.  :)

When I saw this project recommended on the Axolotl discord, my impression was that one could search, and then just edit or delete the results... but I guess for now it's "display and label only".

I consider myself to have a pretty typical workflow - I'm working on a lightweight (couple billion parameter), fast, Apache-licensed summarization model, and am using a heavier-weight model (oasst-Falcon-40B) to generate a training dataset.  But obviously, I need to clean its failures out of it - I've automated keeping its bullet point format consistent, but it'll occasionally do things like talk about how it's an AI model, or mention its prompt, or ignore the language constraints or write in first person because the text was in first person, or whatnot.  I'd been dealing with this somewhat with really long grep strings, but obviously something like lilac - if I could actually delete bad outputs - would be much better.  

Anyway, thanks for your work!

**Comment by nsthorat** [comment]
Great feedback! Let me know if this would make sense for you (since we're thinking of doing exactly that next):

- Label the bad ones (manually, or with slices from enrichments)
- When you export the dataset out of lilac, that's the moment you would say "drop anything tagged with label=bad"

When we export, is there a format that would make most sense for you?

**Comment by nsthorat** [comment]
Question about your editing flow -- do you want to edit rows one-by-one from the UI? Or do you want that to be part of an automated process where we map some edit python function over your rows?

**Comment by dsmilkov** [comment]
Hi, want to also connect on discord: `nikhil_thorat` and `dsmilkov` for higher bandwidth? We'd love to help here.

**Comment by enn-nafnlaus** [comment]
Does #763 make it possible to edit and/or delete (individual or batch) rows in search results?  Because I can't use Lilac without that functionality. How can I clean my dataset if I can't edit it?

**Comment by nsthorat** [comment]
We're going to work on editing & deleting this week, thanks for the awesome feedback :)

**Comment by enn-nafnlaus** [comment]
No, thank you!  :)

**Comment by brilee** [comment]
We have a new set of editing features now! https://docs.lilacml.com/datasets/dataset_edit.html

**Comment by enn-nafnlaus** [comment]
Awesome, can't wait to try it!  :)
