### ISSUE TITLE
Improve our email regex to avoid emails starting with backtick

### ISSUE THREAD

**Issue by dsmilkov** [lilacai/lilac#786]
We should avoid things like \`@app.route and \`@pytest.fixture as emails.

<img width="575" alt="CleanShot 2023-10-24 at 08 44 44@2x" src="https://github.com/lilacai/lilac/assets/2294279/470bd672-2a10-4bf9-a718-ee72012e496d">

**Comment by nsthorat** [comment]
We should switch to presidio: https://github.com/lilacai/lilac/issues/825
