### ISSUE TITLE
Collect labels on created concepts does not seem to work

### ISSUE THREAD

**Issue by dechantoine** [lilacai/lilac#790]
Hello !

Whatever I am trying, I can not get the "collect labels" functionality to work.
I tried with large and small datasets, using local or remote embeddings.
It seems to fetch indefinitely.

I took a look a the codebase but could not find the cause.

Thank you,
Antoine

**Comment by dechantoine** [comment]
BTW, I would like to contribute but I had few tests failed because of loading, I could not find out why. Is your Discord the right place to talk about it ?

**Comment by nsthorat** [comment]
I actually just fixed this bug yesterday but we haven't release a new pip package, I'll do that now!

Discord would be the right place yes :) Let's chat over there!

**Comment by dechantoine** [comment]
Wonderful ! Easy labelling is the key feature that made me chose Lilac 😄

**Comment by nsthorat** [comment]
That's awesome :) We have lots more improvements to that coming soon.

I released a new pip yesterday, let me know if you still have any issues.

Also, happy to jump on quick call if you'd like, could be good to exchange roadmap / your workflow so we can prioritize!
