### ISSUE TITLE
Build error when deploying local project to Hugging Face Spaces

### ISSUE THREAD

**Issue by mikeion** [lilacai/lilac#828]
![build_error](https://github.com/lilacai/lilac/assets/18626318/d4204b8f-eab7-493e-9afb-aeae9345d235)

I have attached an image of the build error I am running into after deploying a local lilac project using `ll.deploy_project()`.

**Comment by nsthorat** [comment]
Hey @mikeion, did you get any errors on the python side on your machine before uploading?

Could you go to your Space settings from the UI and screenshot what the files look like (or give me access to it so I can poke around)? For example, this is our space:

<img width="1336" alt="image" src="https://github.com/lilacai/lilac/assets/1100749/c5e8477f-ed27-444c-a204-53b799e66afc">

**Comment by mikeion** [comment]
Hey @nsthorat -- I believe I had no errors on the Python end when I did the deploy (it did the nice and pretty progress loading bars with the parquet, manifest files). One small thing is that my machine shut down in the middle of computing embeddings, so I know there's some incomplete files in the cache.

My space looks nearly identical to this one, except it's missing the /dist folder (causing the error), looks like I have everything else.

Just made the space public temporarily, going to dm you the link now.

**Comment by mikeion** [comment]
![image](https://github.com/lilacai/lilac/assets/18626318/2dc2e969-26de-46f8-b873-327d4a04b871)
