### ISSUE TITLE
Data not showing up in Hugging Face UI after deploying local project using `ll.deploy_project()`

### ISSUE THREAD

**Issue by mikeion** [lilacai/lilac#834]
After the fix in #828 (https://github.com/lilacai/lilac/issues/828#issue-1981473569), I am now successfully able to deploy a Lilac project in Hugging Face Spaces using `ll.deploy_project()` with my local project.

After setting up the project on an Nvidia T4 medium and with some persistent storage, I seem to be seeing no issues in the logs now, but now it appears to show that it tries to load the dataset in the "Datasets" panel on the left, but then nothing loads. [build_log.txt](https://github.com/lilacai/lilac/files/13284968/build_log.txt)

![image](https://github.com/lilacai/lilac/assets/18626318/202ca9b8-9914-4e17-82b1-e6649f089820)
shows this loading bar, and then nothing happens.

I've attached how my dataset shows up in Hugging Face below:
![image](https://github.com/lilacai/lilac/assets/18626318/9ecc1482-3b8b-4977-9307-5c527b422e4b)

I have made my repository (https://huggingface.co/spaces/mikeion/dissertation_project/) public if this helps. 

Without the T4 (just switched off of it now), this is the memory error I am getting:
![image](https://github.com/lilacai/lilac/assets/18626318/d25ed5ee-d1c7-41f5-8986-ead672d16a8c)

Thanks!

**Comment by nsthorat** [comment]
Ah, sorry about that! Can you share the dataset that got uploaded with me: https://huggingface.co/mikeion/dissertation_project-dissertation-all-help-channels

**Comment by mikeion** [comment]
No worries! Just made it public: It's here: https://huggingface.co/datasets/mikeion/dissertation_project-dissertation-all-help-channels

**Comment by nsthorat** [comment]
Sent a PR to fix this: https://github.com/lilacai/lilac/pull/837
