### ISSUE TITLE
Ergonomics and small bugs with `dataset.map`

### ISSUE THREAD

**Issue by dsmilkov** [lilacai/lilac#915]
Now that we have `dataset.map` in Lilac, filling an issue with ideas for ergonomics/improvements we can make:

### Shorter load API

Currently to make a test dataset from a list of items, we write:

```
items = [
  {'questions': ['A', 'B']},
  {'questions': ['C']},
  {'questions': ['D', 'E']},
]
config = ll.DatasetConfig(
  namespace='local',
  name='tutorial2',
  source=ll.DictSource(items),
)
dataset = ll.create_dataset(config)
```

This can be shorted to ```dataset = ll.from_dicts(items)```. Likewise for other common sources.

### Print first few lines of dataset

I find myself doing a lot of `print(dataset.to_pandas())` after running a `map`, so I can preview first 10 rows of the dataset. This can be slow for large data because we convert the entire dataset and store it in RAM.

Options here:
- `dataset.to_pandas(limit=10)`. This adds a limit to `to_pandas`. The benefit is that notebooks already have a plugin that visualizes a data frame with a nice html, and users can install other plugins for fancier viz.
- Follow HF datasets by adding slicing so users can do: `print(dataset[:10])`
- `dataset.head(limit=...)`, ... where we still give you a data frame.

### The result of dataset.map is empty

```python
result = dataset.map(fn, output_column='test')
print(result) # returns empty list
```
I think this is because `output_column` is provided, but not clear from our API, and surprising as a user.

### ll.create_dataset(overwrite=True)

I found myself doing a lot of `overwrite=True` when calling `ll.create_dataset` as I was rerunning cells to avoid the "Dataset already found". I also noticed a bug where `overwrite=True` doesn't delete the maps/signal enrichment columns from the previous dataset.

### Input columns got renamed during export

If I import a test dataset and export it without any changes:
```
items = [
  {'questions': ['A', 'B']},
  {'questions': ['C']},
  {'questions': ['D', 'E']},
]
dataset = ll.from_dicts(items, ... )
dataset.to_pandas()
```

I get:
```
       questions.*
0      [A, B]
1         [C]
2      [D, E]
```

It's surprising that "questions" got renamed to "questions.*" by Lilac since I never edited the dataset.

### Structuring unstructured data
I wanted to extract a company name and its estimated age from a piece of text. I wrote a simple map using the instructor library and openai model:

<img width="722" alt="CleanShot 2023-12-03 at 16 54 57@2x" src="https://github.com/lilacai/lilac/assets/2294279/5087722b-1960-4fee-8c19-3170067a569b">

And I ran into a few issues:
- dask serialization error:
```
File "stringsource", line 2, in zmq.backend.cython.socket.Socket.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```
- after fixing this, my map started going at the rate of 1ex/sec. I wanted to immediately speed it up:
a) batch multiple inputs in a single request
b) parallelize the network requests with threads
c) immediately see the results of the rows that completed.
d) I edited the map a bit (to avoid depreciation error), but forgot to remove `overwrite=True` so I lost my results when I reran it. A version bit, even with overwrite=True, would have solved this and saved me $$ if I could re-run it and continue from the older version 2: dataset.map(version=2)

**Comment by brilee** [comment]
all of these are fixed now
