### ISSUE TITLE
website: cross-wired footer follow links

### ISSUE THREAD

**Issue by theosanderson** [lilacai/lilac#940]
Hello! In case you wanted to know, the website's footer follow links for GitHub and discord point to the opposite service:
<img width="201" alt="image" src="https://github.com/lilacai/lilac/assets/19732295/cd233bc2-bb06-4ae9-925d-2506eef047ec">

(extreme nitpick :) )

**Comment by nsthorat** [comment]
Theo, how are you? Thanks for filing, I fixed it :)
