### ISSUE TITLE
Dockerfile to build application front and back from source

### ISSUE THREAD

**Issue by aab-saphir** [lilacai/lilac#945]
We have made a lot of modifications from the source code in the FastApi Application. We want to build our modified application in a docker. 
1) I tried to build this dockerfile at the root https://github.com/lilacai/lilac/blob/main/Dockerfile but it don't take in consideration the modifications we have done in the source fastapi application.
2) I tried to enrich the source dockerfile but resulting with node and npm conflict dependencies. I am not an expert in front frameworks.

Here's my Dockerfile

```
FROM python:3.11-slim-bullseye

# Allow statements and log messages to immediately appear in the Knative logs
ENV PYTHONUNBUFFERED True

# Adds GCC and other build tools so we can compile hnswlib and other native/C++ deps.
RUN apt-get update --fix-missing && apt-get install -y --fix-missing build-essential && \
  rm -rf /var/lib/apt/lists/*

# Install Node.js and npm
RUN apt-get update && \
  apt-get install -y nodejs npm && \
  rm -rf /var/lib/apt/lists/*
RUN npm install -g npm@10.2.0

# Install bash
RUN apt-get update && apt-get install -y bash && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install poetry

# Install Node.js dependencies
COPY package.json /app/
COPY package-lock.json /app/
RUN npm install
RUN npm install @openapitools/openapi-generator-cli -g

COPY . /app/
RUN ls -lR .
RUN chmod +x /app/run_server_prod.sh

RUN poetry install

EXPOSE 6432

# Set the working directory in the container.
WORKDIR /app
# Use bash for subsequent commands

CMD ["./run_server_prod.sh"]
```

My docker is not optimized at all, it's still in development actually. 

Have you developed such a Dockerfile ?
Do you have an idea how to fix my Dockerfile to build my application from source ?

**Comment by nsthorat** [comment]
@aab-saphir thanks for filing. Could you share a repo with me so I can take a look / suggest?

Observations:
- lilac isn't in any of the pip installs
- This is the relevant line in our dockerfile `RUN python -m pip install --find-links=dist --upgrade lilac[all]`. This line will 1) try to look for a (from-source built) lilac.whl file in `./dist` and if it doesn't exist, pip installs from the published lilac from pip.
- [This script](https://github.com/lilacai/lilac/blob/main/scripts/deploy_staging.py#L136) is what we use when we develop locally and create docker images (on huggingface). The line I linked you to is the line that creates the local wheel file and puts it in `./dist`. If you want to build from source, you'll want to do something like this.

So you basically need to first build the wheel:

```sh
poetry build -f wheel
```

Put this somewhere, and then in your DockerFile (the name of this file is the output of the first line):

```
pip install source_wheel_name.whl
```

Let me know if that works!

**Comment by aab-saphir** [comment]
> @aab-saphir thanks for filing. Could you share a repo with me so I can take a look / suggest?
> 
> Observations:
> 
> * lilac isn't in any of the pip installs
> * This is the relevant line in our dockerfile `RUN python -m pip install --find-links=dist --upgrade lilac[all]`. This line will 1) try to look for a (from-source built) lilac.whl file in `./dist` and if it doesn't exist, pip installs from the published lilac from pip.
> * [This script](https://github.com/lilacai/lilac/blob/main/scripts/deploy_staging.py#L136) is what we use when we develop locally and create docker images (on huggingface). The line I linked you to is the line that creates the local wheel file and puts it in `./dist`. If you want to build from source, you'll want to do something like this.
> 
> So you basically need to first build the wheel:
> 
> ```shell
> poetry build -f wheel
> ```
> 
> Put this somewhere, and then in your DockerFile (the name of this file is the output of the first line):
> 
> ```
> pip install source_wheel_name.whl
> ```
> 
> Let me know if that works!

Then why in the home Dockerfile does it have the following lines
```
# To reduce the image size, replace lilac[all] with lilac[...] optional deps.
RUN python -m pip install lilac[all]

# Install from the local wheel inside ./dist. This will be a no-op if the wheel is not found.
COPY --chown=user /dis[t] ./dist/
RUN python -m pip install --find-links=dist --upgrade lilac[all]
```

First means, go find the package in pypi. I still found it in [pypi here](https://pypi.org/project/lilac/)
Then install the package from the wheel.
There are two installations.

In my problem, everything I need is in my source code, I don't have to import lilac ?

I am testing it !

**Comment by nsthorat** [comment]
That's a layer cache optimization for docker.

Basically what happens is we first install the pip package from the latest. That will get cached (docker caches line-by-line, a.k.a layer-by-layer).

Then, we install from the local wheel. Only dependencies that are different will get installed.

Without the first line, the install with --find-links will always install the entire set of dependencies from scratch.

I would recommend doing that in your image as well, it will help you speed up the docker build.

Re: everything you need is in your source code -- referring to a fork of lilac? I think you should still probably pip install lilac to help with the build speed thing since the dependencies probably overlap quite a bit.

**Comment by aab-saphir** [comment]
Problem solved thank you.
For others, the simplest steps are:

- Modify source application (as it suits to your needs)
- Build/Push lilac package in a package repository
- Dockerfile: Connect to the package repository
- Dockerfile: Pull/Install package
- Dockerfile: Run command uvicorn lilac.server:app -p ... -h ...
