### ISSUE TITLE
Rendering bug when we have `a[].b[]`

### ISSUE THREAD

**Issue by dsmilkov** [lilacai/lilac#971]
In the dataset below, we have `conversations[].from[]` (note that the `from` itself is an array):

![image](https://github.com/lilacai/lilac/assets/2294279/9744f6ac-73b1-4fb8-816b-49c73ec6908b)

**Comment by tfriedel** [comment]
Not sure if it's a separate issue, but we have  a field
tags[] (i.e. non-nested list) and it only renders the first element instead of the full list.
