### ISSUE TITLE
ShareGPT format: compare to menu should show the title instead of `conversation.0.value`

### ISSUE THREAD

**Issue by dsmilkov** [lilacai/lilac#988]
<img width="655" alt="CleanShot 2023-12-19 at 08 59 03@2x" src="https://github.com/lilacai/lilac/assets/2294279/10f9a992-6fe0-424b-b32b-a0604699f32b">

**Comment by nsthorat** [comment]
This is on purpose. 0 is not necessarily always what you see in the current view (the next row could be GPT).

**Comment by dsmilkov** [comment]
I was think it would be dynamic (a function of the current active row), but maybe that's tricky and not worth it

**Comment by nsthorat** [comment]
It's not possible because it's turn-based, you may have multiple from GPT.
